config/routes.rb
Rails.application.routes.draw do
  resources :sports_venues

  resources :venues

  resources :athletes_teams

  resources :coaches_teams

  resources :sports

  resources :teams do
    member do
      get 'staff'
    end
  end

  resources :teams do
    member do
      get 'roster'
    end
  end

  resources :coaches do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  resources :athletes do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  get 'home/index'

  root to: 'sports#index'

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :venues
  has_and_belongs_to_many :venues, through: :sports

  #  Is sport at facility?
  def is_at_facility?(venue)
    self.venues.include?(venue)
  end

  #  Get all venues sport has a facility at
  def is_at_facility
    self.venues
  end

  #  Get all venues sport does not have a facility at
  def is_not_at_facility
    Venue.all - self.venues
  end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:name, :imageurl)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" class="field">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :imageurl, "Image URL" %>
    <%= f.text_field :imageurl %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :active, "Active Sport" %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit "Save Sport"%>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Editing Sport</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Sports', sports_path, :'data-role' => "button", :'data-icon' => "back" %>
  <%= link_to 'Show Sport', @sport, :'data-role' => "button", :'data-icon' => "eye" %>
</div>

app/views/sports/index.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Sports</h3>

<ul data-role="listview" data-inset="true" data-filter="true" data-autodividers="true">
  <% @sports.each do |sport| %>
    <li><%= link_to sport.name, sport %></li>
  <% end %>
</ul>

<h3 class="ui-bar ui-bar-b ui-corner-all">Sports Administration</h3>

<div data-role="collapsible-set" data-autodividers="true">
    <% @sports.each do |sport| %>
<div data-role="collapsible" data-collapsed="true" data-iconpos="right" data-mini="true">
  <h3><%= h sport.name %></h3>
         <%= link_to 'Edit', edit_sport_path(sport), :'data-role' => 'button', :'data-icon' => 'edit', :'data-inline' => "true", :'data-mini' => "true" %>
         <%= link_to 'Delete', sport, :'data-role' => 'button', :'data-icon' => 'delete', :'data-inline' => "true", method: :delete, data: { confirm: 'Are you sure?' }, :'data-mini' => "true" %>
</div>
    <% end %>
</div>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'New Sport', new_sport_path, :'data-role' => "button", :'data-icon' => "plus" %>
</div>

app/views/sports/new.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">New Sport</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Sport', sports_path, :'data-role' => "button", :'data-icon' => "back" %>
</div>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="ui-bar ui-bar-b ui-corner-all"><%= @sport.name %></h3>

<figure id="pictogram">
  <%= image_tag(@sport.imageurl, alt: @sport.name) %>
</figure>

<ul data-role="listview" data-inset="true">
  <% @teams = Team.where(:sport_id => @sport.id) %>
  <% @teams.each do |team| %>
    <li data-role="list-divider"><%= team.formalname %></li>
    <li><%= link_to 'Team Profile', team %></li>
    <li><%= link_to 'Team Roster', roster_team_path(team) %></a></li>
    <li><%= link_to 'Coaching Staff', staff_team_path(team) %></a></li>
    <li><%= link_to 'Schedule', "#" %></a></li>
  <% end %>

</ul>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Sports', sports_path, :'data-role' => "button", :'data-icon' => "back" %>
  <%= link_to 'Edit Sport', edit_sport_path(@sport), :'data-role' => "button", :'data-icon' => "edit" %>
</div>