config/routes.rb
Rails.application.routes.draw do
  resources :sports_venues

  resources :venues

  resources :athletes_teams

  resources :coaches_teams

  resources :sports

  resources :teams do
    member do
      get 'staff'
    end
  end

  resources :teams do
    member do
      get 'roster'
    end
  end

  resources :coaches do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  resources :athletes do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  get 'home/index'

  root to: 'sports#index'

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  # an athlete can be on more than one team
  has_and_belongs_to_many :teams, through: :athletes

  def fullname
    firstname + " " + lastname
  end

  def lastcommafirst
    lastname + ", " + firstname
  end

  def displayname
    if nickname.blank? then
      dn = sprintf("%s %s", firstname, lastname)
    else
      dn = sprintf("%s (%s) %s", firstname, nickname, lastname)
    end
  end

  #  Is athlete on roster?
  def is_on_roster?(team)
    self.teams.include?(team)
  end

  #  Get all teams coach is on roster of
  def is_on_roster
    self.teams
  end

  #  Get all teams coach is not on roster of
  def is_not_on_roster
    #Team.find(:all) - self.teams
    Team.all - self.teams
  end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy, :teams]

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /athletes/1/team_add?team_id=2
  # (note no real query string, just convenient notation for parameters)
  # ?POST /athletes.json
  def team_add
    #  Convert ids from routing to object
    @athlete = Athlete.find(params[:id])
    @team = Team.find(params[:team])

    unless @athlete.is_on_roster?(@team)
      #  add team to list using << operator
      @athlete.teams << @team
      flash[:notice] = 'Team was successfully added.'
    else
      flash[:error] = 'Athlete was already on roster.'
    end

    # Update Team Captain
    @AthleteTeam = AthletesTeam.find_by(:athlete_id => @athlete.id, :team_id => @team.id)
    @AthleteTeam.update_attributes(:captain => params[:captain], :jerseynumber => params[:jerseynumber], :position => params[:position])


    redirect_to :action => :teams, :id => @athlete
  end

  # POST /athletes/1/team_remove?teams[]=
  def team_remove
    #  Convert ids from routing to object
    @athlete = Athlete.find(params[:id])

    #  Get list of teams to remove from query string
    teams_ids = params[:teams]

    unless teams_ids.blank?
      teams_ids.each do |team_id|
      team = Team.find(team_id)
        if @athlete.is_on_roster?(team)
          logger.info("Removing athlete from team #{team.id}.")
          @athlete.teams.delete(team)
          flash[:notice] = 'Team was successfully deleted.'
        end
      end
    end
    redirect_to :action => :teams, :id => @athlete
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:firstname, :middlename, :lastname, :nickname, :gender, :dob, :gradyear, :active, :height, :weight, :email, :twitter)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for(@athlete) do |f| %>
  <% if @athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% @athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" class="field">
    <%= f.label :firstname, "First Name" %>
    <%= f.text_field :firstname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :middlename, "Middle Name" %>
    <%= f.text_field :middlename %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :gender, "Gender" %>
    <fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
      <%= f.radio_button :gender, 'male' %>
      <%= f.label :gender, 'Male', :value => 'male' %>
      <%= f.radio_button :gender, 'female' %>
      <%= f.label :gender, 'Female', :value => 'female' %>
    </fieldset>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :dob, "Date of Birth" %>
    <%= f.text_field :dob, :type => 'date', :'data-role' => 'date', :'data-inline' => 'true' %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :gradyear, "Graduation Year" %>
    <%= f.select :gradyear, (Time.zone.now.year - 2)..(Time.zone.now.year + 4)%>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :active, "Active Student" %>
    <%= f.check_box :active %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :email, "Email Address" %>
    <%= f.text_field :email %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :twitter, "Twitter Handle" %>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit "Save Athlete" %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Edit Athlete Profile</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Athletes', athletes_path, :'data-role' => 'button', :'data-icon' => "back" %>
  <%= link_to 'Show Athlete', @athlete, :'data-role' => 'button', :'data-icon' => "edit" %>
</div>

app/views/athletes/index.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Athletes</h3>
  
<ul data-role="listview" data-inset="true" data-filter="true" data-autodividers="true">
  <% @athletes.each do |athlete| %>
    <li><%= link_to athlete.lastcommafirst, athlete %></li>
  <% end %>
  <%#= content_tag(:li, fa_icon("check", text: "Bulleted list item")) %>
</ul>
      
<h3 class="ui-bar ui-bar-b ui-corner-all">Athlete Administration</h3>
    
<div data-role="collapsible-set" data-autodividers="true" data-mini="true">
    <% @athletes.each do |athlete| %>
<div data-role="collapsible" data-collapsed="true" data-iconpos="right">
  <h2><%= h athlete.lastcommafirst %></h2>
         <%= link_to 'Edit', edit_athlete_path(athlete), :'data-role' => 'button', :'data-icon' => 'edit', :'data-inline' => "true", :'data-mini' => "true" %>
         <%= link_to 'Delete', athlete, :'data-role' => 'button', :'data-icon' => 'delete', :'data-inline' => "true", method: :delete, data: { confirm: 'Are you sure?' }, :'data-mini' => "true" %>
</div>
    <% end %>
</div>


<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'New Athlete', new_athlete_path, :'data-role' => 'button', :'data-icon' => "plus" %>
</div>

app/views/athletes/new.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">New Athlete</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Athletes', athletes_path, :'data-role' => "button", :'data-icon' => "back" %>
</div>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>

<ul data-role="listview" data-inset="true">
  <li data-role="list-divider"><h1>Athlete Profile:  <%= @athlete.fullname %></h1></li>
  <% if !@athlete.firstname.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">First Name:</div>
      <div class="ui-block-b"><%= @athlete.firstname %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.middlename.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Middle Name:</div>
      <div class="ui-block-b"><%= @athlete.middlename %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.lastname.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Last Name:</div>
      <div class="ui-block-b"><%= @athlete.lastname %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.nickname.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Nickname:</div>
      <div class="ui-block-b"><%= @athlete.nickname %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.gradyear.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Graduation Year:</div>
      <div class="ui-block-b"><%= @athlete.gradyear %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.gender.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Gender:</div>
      <div class="ui-block-b"><%= @athlete.gender.camelize %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.height.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Height:</div>
      <div class="ui-block-b"><%= @athlete.height %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.weight.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Weight:</div>
      <div class="ui-block-b"><%= @athlete.weight %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.dob.blank? %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Date of Birth:</div>
      <div class="ui-block-b"><%= @athlete.dob %></div>
    </div>
  </li>
  <% end %>
  <% if !@athlete.email.blank? %>
    <li><a  href="<%= sprintf("mailto:%s", @athlete.email) %>">Email Address</a><span class="ui-li-aside" data-rel="external""><%= @athlete.email %></span></li>
  <% end %>
  <% if !@athlete.twitter.blank? %>
    <li><a  href="<%= sprintf("https://twitter.com/%s", @athlete.twitter.delete("@")) %>" data-rel="external">Twitter Handle</a><span class="ui-li-aside"><%= @athlete.twitter %></span></li>
  <% end %>
</ul>

  <% if @athlete.teams.count > 0 %>
  <h3><%= @athlete.firstname %> is a member of the following teams:</h3>
    <ul data-role="listview" data-inset="true" data-filter="true">
      <% @athlete.teams.each do |t| %>
        <% tc = AthletesTeam.find_by(:team_id => t.id, :athlete_id => @athlete.id) %>
        <li><%= link_to(t.formalname, t) %><span class="ui-li-aside"><%= tc.captain ? "Team Captain" : "" %></span></li>
      <% end %>
    </ul>
  <% else %>
    <%= @athlete.firstname %> is not currently on any team roster.
  <% end %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Athletes', athletes_path, :'data-role' => 'button', :'data-icon' => "back" %>
  <%= link_to 'Edit Athlete', edit_athlete_path(@athlete), :'data-role' => 'button', :'data-icon' => "edit" %>
  <%= link_to 'Edit Teams', teams_athlete_path(@athlete), :'data-role' => 'button', :'data-icon' => "edit" %>

</div>

app/views/athletes/teams.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all"><%= @athlete.displayname %>'s Teams</h3>

  <% if @athlete.teams.count > 0 %>
    <%#= @athlete.teams.collect {|t| link_to(t.formalname, t)}.join(", ").html_safe %>
    <ul data-role="listview" data-inset="true" data-filter="true">
      <% @athlete.teams.each do |t| %>
        <% hc = AthletesTeam.find_by(:team_id => t.id, :athlete_id => @athlete.id) %>
        <li><%= link_to(t.formalname, t) %><span class="ui-li-aside"><%= hc.captain ? "Captain" : "" %></span></li>
      <% end %>
    </ul>
  <% else %>
    <%= @athlete.firstname %> is not currently on any team roster.
  <% end %>

<h3 class="ui-bar ui-bar-b ui-corner-all">Add <%= @athlete.displayname %> to Team Roster</h3>

<% if @athlete.teams.count < Team.count then %>

  <%= form_tag(team_add_athlete_path(@athlete)) do %>
    <div class="field">
      <%= label_tag "Select Team" %>
      <%= select_tag(:team, options_from_collection_for_select(@athlete.is_not_on_roster, :id, :formalname)) %>
    </div>
    <div data-role="fieldcontain" class="field">
      <%= label_tag "Captain" %>
      <%= select_tag(:captain, options_for_select([["Yes", true], ["No", false]]), :'data-role' => "slider") %>
    </div>
    <div data-role="fieldcontain" class="field">
      <%= label_tag "Jersey Number" %>
      <%= select_tag(:jerseynumber, options_for_select((0..99))) %>
    </div>
    <div data-role="fieldcontain" class="field">
      <%= label_tag "Position(s)" %>
      <%= text_field_tag(:position) %>
    </div>
    <div class="field">
      <%= submit_tag 'Add To Roster', :'data-role' => 'button', :'data-inline' => "false", :'data-mini' => "true", :'data-inline' => "true" %>
    </div>
  <% end %>
<% else %>
  <p><%=h @athlete.displayname %> is on every roster.</p>
<% end %>


<% if @athlete.teams.count > 0 %>
  <h3 class="ui-bar ui-bar-b ui-corner-all">Remove <%= @athlete.displayname %> from Team Roster</h3>
  <%= form_tag(team_remove_athlete_path(@athlete)) do %>
    <div class="field">
      <%= select_tag("teams[]", options_from_collection_for_select(@athlete.is_on_roster, :id, :formalname), :multiple => true, :prompt => "Select Teams", :'data-native-menu' => false ) %>
    </div>
    <div data-role="fieldcontain" class="field">
      <%= submit_tag 'Remove From Roster', :'data-role' => 'button', :'data-inline' => "false", :'data-mini' => "true", :'data-inline' => "true", :'data-icon' => "delete" %>
    </div>
  <% end %>
<% else %>
  <!--<%#= @athlete.firstname %> is not currently on any team roster.-->
<% end %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to "Back to Athlete", @athlete, :'data-role' => 'button', :'data-inline' => "false", :'data-mini' => "true", :'data-inline' => "true", :'data-icon' => "back" %>
</div>