config/routes.rb
Rails.application.routes.draw do
  resources :sports_venues

  resources :venues

  resources :athletes_teams

  resources :coaches_teams

  resources :sports

  resources :teams do
    member do
      get 'staff'
    end
  end

  resources :teams do
    member do
      get 'roster'
    end
  end

  resources :coaches do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  resources :athletes do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  get 'home/index'

  root to: 'sports#index'

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  # a coach can coach more than one team
  has_and_belongs_to_many :teams, through: :coaches
  has_and_belongs_to_many :sports, through: :teams

  def fullname
    firstname + " " + lastname
  end

  def lastcommafirst
    lastname + ", " + firstname
  end

  def displayname
    if nickname.blank? then
      dn = sprintf("Coach %s %s", firstname, lastname)
    else
      dn = sprintf("Coach %s (%s) %s", firstname, nickname, lastname)
    end
  end

  #  Is coach on staff?
  def is_on_staff?(team)
    self.teams.include?(team)
  end

  #  Get all teams coach is on staff of
  def is_on_staff
    self.teams
  end

  #  Get all teams coach is not on staff of
  def is_not_on_staff
    #Team.find(:all) - self.teams
    Team.all - self.teams
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # GET /coaches/1/teams
  def teams
    @coach = Coach.find(params[:id])
    @teams = @coach.teams
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /coaches/1/team_add?team_id=2
  # (note no real query string, just convenient notation for parameters)
  # ?POST /coaches.json
  def team_add
    #  Convert ids from routing to object
    @coach = Coach.find(params[:id])
    @team = Team.find(params[:team])

    unless @coach.is_on_staff?(@team)
      #  add team to list using << operator
      @coach.teams << @team
      flash[:notice] = 'Team was successfully added.'
    else
      flash[:error] = 'Coach was already on staff.'
    end

    # Update Head Coach
    @CoachTeam = CoachesTeam.find_by(:coach_id => @coach.id, :team_id => @team.id)
    @CoachTeam.update_attributes(:headcoach => params[:headcoach])


    redirect_to :action => :teams, :id => @coach
  end

  # POST /coaches/1/team_remove?teams[]=
  def team_remove
    #  Convert ids from routing to object
    @coach = Coach.find(params[:id])

    #  Get list of teams to remove from query string
    teams_ids = params[:teams]

    unless teams_ids.blank?
      teams_ids.each do |team_id|
      team = Team.find(team_id)
        if @coach.is_on_staff?(team)
          logger.info("Removing coach from team #{team.id}.")
          @coach.teams.delete(team)
          flash[:notice] = 'Team was successfully deleted.'
        end
      end
    end
    redirect_to :action => :teams, :id => @coach
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:firstname, :middlename, :lastname, :nickname, :active, :email, :twitter)
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% @coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" class="field">
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :middlename, "Middle Name" %><br>
    <%= f.text_field :middlename %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :active, "Active Coach" %><br>
    <%= f.check_box :active %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :email, "Email Address" %><br>
    <%= f.text_field :email %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :twitter, "Twitter Username" %><br>
    <%= f.text_field :twitter %>
  </div>
  <div data-role="fieldcontain" class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Edit Coach Profile</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Coaches', coaches_path, :'data-role' => 'button', :'data-icon' => "back" %>
  <%= link_to 'Show Coach', @coach, :'data-role' => 'button', :'data-icon' => "user" %>
</div>

app/views/coaches/index.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Coaches</h3>


<ul data-role="listview" data-inset="true" data-filter="true" data-autodividers="true">
  <% @coaches.each do |coach| %>
    <li><%= link_to coach.lastcommafirst, coach %></li>
  <% end %>
  <%#= content_tag(:li, fa_icon("check", text: "Bulleted list item")) %>
</ul>

<h3 class="ui-bar ui-bar-b ui-corner-all">Coach Administration</h3>

<div data-role="collapsible-set" data-autodividers="true" data-mini="true">
    <% @coaches.each do |coach| %>
<div data-role="collapsible" data-collapsed="true" data-iconpos="right">
  <h2><%= h coach.lastcommafirst %></h2>
         <%= link_to 'Edit', edit_coach_path(coach), :'data-role' => 'button', :'data-icon' => 'edit', :'data-inline' => "true", :'data-mini' => "true" %>
         <%= link_to 'Delete', coach, :'data-role' => 'button', :'data-icon' => 'delete', :'data-inline' => "true", method: :delete, data: { confirm: 'Are you sure?' }, :'data-mini' => "true" %>
</div>
    <% end %>
</div>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'New Coach', new_coach_path, :'data-role' => 'button', :'data-icon' => 'plus' %>
</div>

app/views/coaches/new.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">New Coach</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Coaches', coaches_path, :'data-role' => 'button', :'data-icon' => "back" %>
</div>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="ui-bar ui-bar-b ui-corner-all"><%=h @coach.displayname %></h3>

<ul data-role="listview" data-inset="true">
  <% if !@coach.email.blank? %>
    <li><a  href="<%= sprintf("mailto:%s", @coach.email) %>">Email Address</a><span class="ui-li-aside" data-rel="external""><%= @coach.email %></span></li>
  <% end %>
  <% if !@coach.twitter.blank? %>
    <li><a  href="<%= sprintf("https://twitter.com/%s", @coach.twitter.delete("@")) %>" data-rel="external">Twitter Handle</a><span class="ui-li-aside"><%= @coach.twitter %></span></li>
  <% end %>
</ul>

  <h3>Teams:</h3>
  <% if @coach.teams.count > 0 %>
    <%#= @coach.teams.collect {|t| link_to(t.formalname, t)}.join(", ").html_safe %>
    <ul data-role="listview" data-inset="true" data-filter="true">
      <% @coach.teams.each do |t| %>
        <% hc = CoachesTeam.find_by(:team_id => t.id, :coach_id => @coach.id) %>
        <li><%= link_to(t.formalname, t) %><span class="ui-li-aside"><%= hc.headcoach ? "Head Coach" : "" %></span></li>
      <% end %>
    </ul>
  <% else %>
    Not currently on any coaching staff.
  <% end %>


<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Coaches', coaches_path, :'data-role' => 'button', :'data-icon' => "back" %>
  <%= link_to 'Edit Coach', edit_coach_path(@coach), :'data-role' => 'button', :'data-icon' => "edit" %>
  <%= link_to 'Edit Teams', teams_coach_path(@coach), :'data-role' => 'button', :'data-icon' => "edit" %>
</div>

app/views/coaches/teams.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all"><%= @coach.fullname %>'s Teams</h3>

  <% if @coach.teams.count > 0 %>
    <%#= @coach.teams.collect {|t| link_to(t.formalname, t)}.join(", ").html_safe %>
    <ul data-role="listview" data-inset="true" data-filter="true">
      <% @coach.teams.each do |t| %>
        <% hc = CoachesTeam.find_by(:team_id => t.id, :coach_id => @coach.id) %>
        <li><%= link_to(t.formalname, t) %><span class="ui-li-aside"><%= hc.headcoach ? "Head Coach" : "" %></span></li>
      <% end %>
    </ul>
  <% else %>
    Not currently on any coaching staff.
  <% end %>

<h2>Add <%= @coach.fullname %> to Coaching Staff</h2>

<% if @coach.teams.count < Team.count then %>

  <%= form_tag(team_add_coach_path(@coach)) do %>
    <div class="field">
      <%= label_tag "Select Team" %>
      <%= select_tag(:team, options_from_collection_for_select(@coach.is_not_on_staff, :id, :formalname)) %>
    </div>
    <div data-role="fieldcontain" class="field">
      <%= label_tag "Head Coach" %>
      <%= select_tag(:headcoach, options_for_select([["Yes", true], ["No", false]]), :'data-role' => "slider") %>
    </div>

    <div class="field">
      <%= submit_tag 'Add To Staff', :'data-role' => 'button', :'data-inline' => "false", :'data-mini' => "true", :'data-inline' => "true" %>
    </div>
  <% end %>
<% else %>
  <p><%=h @coach.fullname %> is on every staff.</p>
<% end %>

<h2>Remove <%= @coach.fullname %> from Coaching Staff</h2>

  <% if @coach.teams.count > 0 %>
  <%= form_tag(team_remove_coach_path(@coach)) do %>
    <div class="field">
      <%= select_tag("teams[]", options_from_collection_for_select(@coach.is_on_staff, :id, :formalname), :multiple => true, :prompt => "Select Teams", :'data-native-menu' => false ) %>
    </div>
    <div data-role="fieldcontain" class="field">
      <%= submit_tag 'Remove From Staff', :'data-role' => 'button', :'data-inline' => "false", :'data-mini' => "true", :'data-inline' => "true", :'data-icon' => "delete" %>
    </div>
  <% end %>
  <% else %>
    Not currently on any coaching staff.
  <% end %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to "Back to Coach", @coach, :'data-role' => 'button', :'data-inline' => "false", :'data-mini' => "true", :'data-inline' => "true", :'data-icon' => "back" %>
</div>