config/routes.rb
Rails.application.routes.draw do
  resources :sports_venues

  resources :venues

  resources :athletes_teams

  resources :coaches_teams

  resources :sports

  resources :teams do
    member do
      get 'staff'
    end
  end

  resources :teams do
    member do
      get 'roster'
    end
  end

  resources :coaches do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  resources :athletes do
    member do
      get :teams
      post 'team_add'
      post 'team_remove'
    end
  end

  get 'home/index'

  root to: 'sports#index'

end

app/models/athletes_team.rb
class AthletesTeam < ActiveRecord::Base
  belongs_to :athlete
  belongs_to :team
end

app/controllers/athletes_teams_controller.rb
class AthletesTeamsController < ApplicationController
  before_action :set_athletes_team, only: [:show, :edit, :update, :destroy]

  # GET /athletes_teams
  # GET /athletes_teams.json
  def index
    @athletes_teams = AthletesTeam.all
  end

  # GET /athletes_teams/1
  # GET /athletes_teams/1.json
  def show
  end

  # GET /athletes_teams/new
  def new
    @athletes_team = AthletesTeam.new
  end

  # GET /athletes_teams/1/edit
  def edit
  end

  # POST /athletes_teams
  # POST /athletes_teams.json
  def create
    @athletes_team = AthletesTeam.new(athletes_team_params)

    respond_to do |format|
      if @athletes_team.save
        format.html { redirect_to @athletes_team, notice: 'Athletes team was successfully created.' }
        format.json { render :show, status: :created, location: @athletes_team }
      else
        format.html { render :new }
        format.json { render json: @athletes_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes_teams/1
  # PATCH/PUT /athletes_teams/1.json
  def update
    respond_to do |format|
      if @athletes_team.update(athletes_team_params)
        format.html { redirect_to @athletes_team, notice: 'Athletes team was successfully updated.' }
        format.json { render :show, status: :ok, location: @athletes_team }
      else
        format.html { render :edit }
        format.json { render json: @athletes_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes_teams/1
  # DELETE /athletes_teams/1.json
  def destroy
    @athletes_team.destroy
    respond_to do |format|
      format.html { redirect_to athletes_teams_url, notice: 'Athletes team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athletes_team
      @athletes_team = AthletesTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athletes_team_params
      params.require(:athletes_team).permit(:team_id, :athlete_id, :captain, :position, :jerseynumber)
    end
end

app/helpers/athletes_teams_helper.rb
module AthletesTeamsHelper
end

app/views/athletes_teams/_form.html.erb
<%= form_for(@athletes_team) do |f| %>
  <% if @athletes_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athletes_team.errors.count, "error") %> prohibited this athletes_team from being saved:</h2>

      <ul>
      <% @athletes_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" class="field">
    <%= f.label :team_id, "Team" %>
    <%= f.collection_select :team_id, Team.all, :id, :formalname %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :athlete_id, "Athlete" %>
    <%= f.collection_select :athlete_id, Athlete.all, :id, :lastcommafirst%>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :captain %>
    <%= f.check_box :captain %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :jerseynumber, "Jersey Number" %>
    <%= f.text_field :jerseynumber %>
  </div>
  <div data-role="fieldcontain" class="field">
    <%= f.label :position, "Position(s)" %>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit "Save Team Athlete" %>
  </div>
<% end %>

app/views/athletes_teams/edit.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Edit Team Athletes</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Team Athletes', athletes_teams_path, :'data-role' => "button", :'data-icon' => "back" %>
  <%= link_to 'Show Team Athletes', @athletes_team, :'data-role' => "button", :'data-icon' => "eye" %>
</div>

app/views/athletes_teams/index.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">Team Athletes</h3>

<div data-role="collapsible-set" data-autodividers="true" data-mini="true" data-collapsed-icon="carat-r" data-expanded-icon="carat-d">
    <% tid = nil %>
    <% @athletes_teams.each do |at| %>
      <% if !tid.nil? && tid != at.team.id %>
          </div>
        </div>
      <% end %>
      <% if tid != at.team.id %>
        <div data-role="collapsible" data-mini="true" data-inset="true">
          <h3><%= at.team.formalname %></h3>
          <div data-role="collapsible-set" data-mini="true" data-collapsed-icon="carat-r" data-expanded-icon="carat-d">
      <% end %>
      <div data-role="collapsible" data-collapsed="true" data-inset="true">
        <h1><%= at.athlete.fullname %></h1>
        <div data-role="controlgroup" data-type="horizontal" data-mini="true">
          <%= link_to 'Show', at, :'data-role' => 'button', :'data-icon' => "eye" %>
          <%= link_to 'Edit', edit_athletes_team_path(at), :'data-role' => "button", :'data-icon' => "edit" %>
          <%= link_to 'Destroy', at, method: :delete, data: { confirm: 'Are you sure?' }, :'data-role' => "button", :'data-icon' => "delete" %>
        </div>
      </div>
      <% tid = at.team.id %>
    <% end %>
    </div>
</div>


<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'New Team Athletes', new_athletes_team_path, :'data-role' => "button", :'data-icon' => "plus" %>
</div>

app/views/athletes_teams/new.html.erb
<h3 class="ui-bar ui-bar-b ui-corner-all">New Team Athlete</h3>

<%= render 'form' %>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Team Athletes', athletes_teams_path, :'data-role' => "button", :'data-icon' => "back" %>
</div>

app/views/athletes_teams/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="ui-bar ui-bar-b ui-corner-all"><%= @athletes_team.team.formalname %>:  <%= @athletes_team.athlete.fullname %></h3>
    
<figure id="pictogram">
  <%= image_tag(@athletes_team.team.sport.imageurl, alt: @athletes_team.team.formalname) %>
</figure>
          
<ul data-role="listview" data-inset="true">
  <li data-role="list-divider">Profile</li>
  <%if @athletes_team.captain %>
    <li>Team Captain</li>
  <% end %>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Jersey Number:</div>
      <div class="ui-block-b"><%= @athletes_team.jerseynumber %>
    </div>
  </li>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Position(s):</div>
      <div class="ui-block-b"><%= @athletes_team.position %>
    </div>
  </li>
  <li>
    <div class="ui-grid-a">
      <div class="ui-block-a">Graduation Year:</div>
      <div class="ui-block-b"><%= @athletes_team.athlete.gradyear %>
    </div>
  </li>
  <li><%= link_to @athletes_team.team.formalname, team_path(@athletes_team.team_id) %></li>
  <li><%= link_to @athletes_team.athlete.fullname, athlete_path(@athletes_team.athlete_id) %></li>
</ul>

<div data-role="footer" data-position="fixed" data-tap-toggle="false" class="ui-bar">
  <%= link_to 'Back to Team Athletes', athletes_teams_path, :'data-role' => "button", :'data-icon' => "back" %>
  <%= link_to 'Edit Team Athlete', edit_athletes_team_path(@athletes_team), :'data-role' => "button", :'data-icon' => "edit" %>
</div>